# Example secrets with placeholder values. Edit or replace after applying.
apiVersion: v1
kind: Secret
metadata:
  name: taskstack-secrets
  namespace: taskstack
type: Opaque
data:
  # base64 encoded values; run:  echo -n 'value' | base64
  AUTH_DB_USER: YXV0aHVzZXI=
  AUTH_DB_PASS: YXV0aHBhc3M=
  TASK_DB_USER: dGFza3VzZXI=
  TASK_DB_PASS: dGFza3Bhc3M=
  SMTP_HOST: ""
  SMTP_PORT: NTg3
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: bm8tcmVwbHlAZXhhbXBsZS5jb20=
